version: '2.1'
orbs:
  python: circleci/python@1.1.0
  gcp-cli: circleci/gcp-cli@2.1.0
jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            pip install pytest
          name: instalando pytest
      - run:
          command: |
            pytest 
          name: Test
  deploy:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Credentials
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV
            echo ${GCP_PROJECT_KEY} | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json
            echo 'export GOOGLE_CLOUD_KEYS=$(cat $HOME/gcloud-service-key.json)' >> $BASH_ENV
            echo 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV
      - gcp-cli/install_and_initialize_cli:
          name: instalando e iniciando gcp cli
          executor: gcp-cli/default
          gcloud-service-key: GOOGLE_CLOUD_KEYS
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
workflows:
  main:
    jobs:
      - test
      - deploy
