version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    machine:
      - image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: echo "this is the build job from Mario"
  test:
    machine:
      - image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: echo "this is the test job from Mario"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
