version: 2.1

# Define the jobs we want to run for this project
jobs:
  working_directory: ~/my-ci-cd-test
  test:
      docker:
          image: cimg/python:3.10.1
      steps:
          - checkout
          - run: sudo chown -R circleci:circleci /usr/local/bin
          - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
          - restore_cache:  # ensure this step occurs *before* installing dependencies
              key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          - run:
                name: Instalar pytest
                command: |
                    sudo pip install pytest
          - run: 
                name: test 
                command: pytest 
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
