version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
      docker:
          image: python:3.7
      - run:
          name: Run tests
          command: |
            pip install virtualenv
	          virtualenv .venv
	          source .venv/bin/activate
            pip install pytest
            pytest test
          no_output_timeout: 1h
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
