version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
      docker:
        - image: circleci/python:3.7
      steps:
        - run:
            name: descargando git
            command: |
              sudo apt install git
        - run: 
            name: clonando repositorio
            comman: |
              git clone https://github.com/CallejasJr/my-ci-cd-test.git
        - run:
            name: Run install and activate virtual env
            command: |
              pip install virtualenv
              virtualenv .venv
              source .venv/bin/activate
            no_output_timeout: 1h
        - run:
            name: instalar pytest
            command: |
              pip install pytest
        - run:
            name: listando directorio
            command: |
              ls
        - run:
            name: correr test
            command: |
              pytest
          
# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
